#!/usr/bin/env bash

EXIT_CODE_DURATION_MISSING=3
EXIT_CODE_MAXIMUM_DURATION_MISSING=4

if [ -z "$DURATION" ]; then
  exit "$EXIT_CODE_DURATION_MISSING"
fi

if [ -z "$MAXIMUM_DURATION" ]; then
  exit "$EXIT_CODE_MAXIMUM_DURATION_MISSING"
fi

SHOULD_RETRY="false"
if [ $DURATION -lt $MAXIMUM_DURATION ] || [ $DURATION = $MAXIMUM_DURATION ]; then
  SHOULD_RETRY="true"
fi

echo "$SHOULD_RETRY"
