#!/usr/bin/env bash

EXIT_CODE_CREATED_AT_MISSING=3
EXIT_CODE_UPDATED_AT_MISSING=4
EXIT_CODE_CREATED_AT_NOT_A_DATE=5
EXIT_CODE_UPDATED_AT_NOT_A_DATE=6

if [ -z "$CREATED_AT" ]; then
  exit "$EXIT_CODE_CREATED_AT_MISSING"
fi

if [ -z "$UPDATED_AT" ]; then
  exit "$EXIT_CODE_UPDATED_AT_MISSING"
fi

CREATED_AT_TIMESTAMP=$(date --date "$CREATED_AT" +%s 2>/dev/null)
if [ "" = "$CREATED_AT_TIMESTAMP" ]; then
  exit "$EXIT_CODE_CREATED_AT_NOT_A_DATE"
fi

UPDATED_AT_TIMESTAMP=$(date --date "$UPDATED_AT" +%s 2>/dev/null)
if [ "" = "$UPDATED_AT_TIMESTAMP" ]; then
  exit "$EXIT_CODE_UPDATED_AT_NOT_A_DATE"
fi

DURATION=$(("$UPDATED_AT_TIMESTAMP" - "$CREATED_AT_TIMESTAMP"))
echo "$DURATION"
