services:
    _defaults:
        autowire: true
        autoconfigure: true

    GuzzleHttp\Handler\MockHandler:
        public: true
        class: GuzzleHttp\Handler\MockHandler

    GuzzleHttp\HandlerStack:
        class: GuzzleHttp\HandlerStack
        factory: ['GuzzleHttp\HandlerStack', 'create']
        arguments:
            $handler: '@GuzzleHttp\Handler\MockHandler'

    App\Tests\Services\HttpResponseFactory:
        public: true

    App\Services\InstanceCollectionHydrator:
        public: true

    App\Services\FloatingIpRepository:
        arguments:
            $dropletTag: '%env(DIGITALOCEAN_DROPLET_TAG)%'

    App\Services\FloatingIpManager:
        public: true

    App\Services\ActionRepository:
        public: true

    App\Services\ImageRepository:
        public: true
        arguments:
            $imageName: '%worker_manager_image%'
