version: "3"

services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_EXPOSED_PORT}:5432

  caddy:
    image: caddy:2.4.5
    container_name: caddy
    restart: unless-stopped
    environment:
      DOMAIN: ${CADDY_DOMAIN:-localhost}
      TLS_INTERNAL: ${CADDY_TLS_INTERNAL:-internal}
    ports:
      - "443:443"
    links:
      - app:app
    volumes:
      - ./caddy/index.php:/app/public/index.php
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile

  app:
    image: ghcr.io/smartassert/worker-manager:${VERSION}
    container_name: worker-manager
    restart: always
    env_file: app.env
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/worker-db?serverVersion=12&charset=utf8
      MESSENGER_TRANSPORT_DSN: doctrine://default
    depends_on:
      - postgres
