services:
  caddy:
    image: caddy:2.4.5
    container_name: caddy
    restart: unless-stopped
    environment:
      DOMAIN: ${CADDY_DOMAIN:-localhost}
      TLS_INTERNAL: ${CADDY_TLS_INTERNAL:-}
      IP: ${CADDY_IP:-}
    ports:
      - "443:443"
      - "80:80"
    links:
      - app:app
    volumes:
      - ~/caddy/index.php:/app/public/index.php
      - ~/caddy/Caddyfile:/etc/caddy/Caddyfile

  app:
    image: ghcr.io/smartassert/users:${VERSION}
    container_name: app
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
