name: image.build

on:
  workflow_dispatch:
    inputs:
      service_id:
        description: The service for which the configuration is being stored
        required: true

jobs:
  setup:
    name: Setup ${{ github.event.inputs.service_id }}
    runs-on: ubuntu-latest

    steps:
      - name: Output workflow_dispatch inputs
        env:
          INPUTS: ${{ toJson(github.event.inputs) }}
        run: echo "$INPUTS"

  verify-setup:
    name: Verify setup
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Output
        env:
          OUTPUTS: ${{ toJson(needs.setup.outputs) }}
        run: echo "$OUTPUTS"

      - name: Verify service_id is set
        env:
          SERVICE_ID: ${{ github.event.inputs.service_id }}
        run: |
          [[ -n "$SERVICE_ID" ]] || (echo "service_id not set" && exit 1)

      - name: Verify service configuration exists
        env:
          ENV_FILE_PATH: ./services/${{ github.event.inputs.service_id }}/configuration.env
          SERVICE_ID: ${{ github.event.inputs.service_id }}
        run: ./ci/scripts/check-service-configuration-exists.sh
