name: Create instance

on:
  workflow_dispatch:

jobs:
  create:
    name: Create instance
    runs-on: ubuntu-latest
    env:
      DIGITALOCEAN_API_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout bash-read-env-file
        uses: actions/checkout@v2
        with:
          repository: smartassert/bash-read-env-file
          path: ./vendor/smartassert/bash-read-env-file
          ref: main

      - name: Checkout bash-ga-deploy-tools
        uses: actions/checkout@v2
        with:
          repository: smartassert/bash-ga-deploy-tools
          path: ./vendor/smartassert/bash-ga-deploy-tools
          ref: main

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8

      - name: Download dependencies
        uses: php-actions/composer@v6
        with:
          args: --ignore-platform-reqs --quiet
          working_dir: app

      - name: Read build config
        id: worker-manager-image
        env:
          ENV_FILE_PATH: ./worker-manager-image.env
        run: ./vendor/smartassert/bash-read-env-file/src/read-env-file-ga.sh

      - name: Check snapshot exists
        env:
          IMAGE_ID: ${{ steps.worker-manager-image.outputs.WORKER_MANAGER_IMAGE }}
          EXPECTED_EXISTS: "true"
        run: ./vendor/smartassert/bash-ga-deploy-tools/src/digitalocean-snapshot/verify-existence.sh

      - name: Create
        id: instance
        env:
          WORKER_MANAGER_IMAGE: ${{ steps.worker-manager-image.outputs.WORKER_MANAGER_IMAGE }}
        run: |
          CREATE_OUTPUT=$(php app/bin/console app:instance:create)
          echo "::set-output name=id::$(echo $CREATE_OUTPUT | jq ".id")"

      - name: Health check
        env:
          COMMAND: "php app/bin/console app:instance:is-healthy --id=${{ steps.instance.outputs.id }}"
        run: ./ci/scripts/execute-command-output-json.sh

      - name: Remove instance if health check failed
        if:  ${{ failure() }}
        env:
          INSTANCE_ID: ${{ steps.instance.outputs.id }}
        run: php app/bin/console app:instance:destroy --id=$INSTANCE_ID
