name: Destroy Inactive Instances

on:
  pull_request:
    branches:
      - github-49
  workflow_dispatch:

jobs:
  assign:
    name: Destroy instances
    runs-on: ubuntu-latest
    env:
      DIGITALOCEAN_API_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8

      - name: Download dependencies
        uses: php-actions/composer@v6
        with:
          args: --ignore-platform-reqs --quiet
          working_dir: app

      - name: Get floating IP
        id: ip
        run: echo "::set-output name=value::$(php app/bin/console app:ip:get)"

      - name: Get list of instances to destroy
        id: instances
        if: ${{ steps.ip.outputs.value != '' }}
        env:
          IP: ${{ steps.ip.outputs.value }}
        run: |
          INSTANCES=$(php app/bin/console app:instance:list --with-empty-message-queue --without-ip=$IP)
          INSTANCE_IDS=$(echo $INSTANCES | jq ".instances[] | .id")

          echo "::set-output name=ids::$INSTANCE_IDS"

      - name: Destroy matching instances
        env:
          INSTANCE_IDS: ${{ steps.instances.outputs.ids }}
        run: |
          for ID in $INSTANCE_IDS; do
            echo -n "Destroying $ID ... "
            php app/bin/console app:instance:destroy --id=$ID
          done
