name: Create instance

on:
  workflow_dispatch:
  schedule:
    - cron: "10 * * * *"

jobs:
  commit:
    name: Create instance
    runs-on: ubuntu-latest
    env:
      DIGITALOCEAN_API_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Expose worker manager image variable
        id: worker-manager-image
        run:
          export echo $(cat worker-manager-image.env | tr '\n' ' ')

          echo "::set-output name=id::$WORKER_MANAGER_IMAGE"

      - name: Check snapshot exists
        env:
          WORKER_MANAGER_IMAGE: ${{ steps.worker-manager-image.outputs.id }}
        run: |
          cd app
          php bin/console app:snapshot:exists --expect-exists 1

      - name: Create
        env:
          WORKER_MANAGER_IMAGE: ${{ steps.worker-manager-image.outputs.id }}
        run: |
          cd app
          php bin/console app:instance:create
