name: Assign IP to Current Instance

on:
  workflow_dispatch:

jobs:
  assign:
    name: Assign IP
    runs-on: ubuntu-latest
    env:
      DIGITALOCEAN_API_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8

      - name: Download dependencies
        uses: php-actions/composer@v6
        with:
          args: --ignore-platform-reqs --quiet
          working_dir: app

      - name: Get floating IP
        id: ip
        env:
          INSTANCE_COLLECTION_TAG: worker-manager
        run: |
          echo "::set-output name=value::$(php app/bin/console app:ip:get)"

      - name: Re-assign IP if found
        if: ${{ steps.ip.outputs.value != '' }}
        env:
          INSTANCE_COLLECTION_TAG: worker-manager
          COMMAND: "php app/bin/console app:ip:assign"
        run: ./ci/scripts/execute-command-output-json.sh

      - name: Create IP if none found
        if: ${{ steps.ip.outputs.value == '' }}
        env:
          INSTANCE_COLLECTION_TAG: worker-manager
          COMMAND: "php app/bin/console app:ip:create"
        run: ./ci/scripts/execute-command-output-json.sh
