name: Assign IP to Current Instance

on:
  workflow_dispatch:

jobs:
  assign:
    name: Assign IP
    runs-on: ubuntu-latest
    env:
      DIGITALOCEAN_API_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8

      - name: Download dependencies
        uses: php-actions/composer@v6
        with:
          args: --ignore-platform-reqs --quiet
          working_dir: app

      - name: Expose worker manager image variable
        id: worker-manager-image
        run:
          export echo $(cat worker-manager-image.env | tr '\n' ' ')

          echo "::set-output name=id::$WORKER_MANAGER_IMAGE"

      - name: Get floating IP
        id: has-ip
        run: |
          HAS_IP="true"
          if [ -z "$(php app/bin/console app:ip:get)" ]; then
            HAS_IP="false"
          fi

          echo "::set-output name=value::$HAS_IP"

      - name: Create IP if none found
        if: ${{ steps.has-ip.outputs.value == 'false' }}
        run: ./.github/workflows/ip.create.sh

      - name: Re-assign IP if found
        if: ${{ steps.has-ip.outputs.value == 'true' }}
        run: ./.github/workflows/ip.assign.sh
