name: Assign IP to Current Instance

on:
  workflow_dispatch:
    inputs:
      service_id:
        description: Service for which to create an instance
        required: true

jobs:
  assign:
    name: Assign IP
    runs-on: ubuntu-latest
    env:
      DIGITALOCEAN_API_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8

      - name: Download dependencies
        uses: php-actions/composer@v6
        with:
          args: --ignore-platform-reqs --quiet
          working_dir: app

      - name: Read service configuration
        id: build-config
        env:
          ENV_FILE_PATH: ./services/${{ github.event.inputs.service_id }}/configuration.env
          SERVICE_ID: ${{ github.event.inputs.service_id }}
        run: |
          ./ci/scripts/check-service-configuration-exists.sh
          ./vendor/smartassert/bash-read-env-file/src/read-env-file-ga.sh

      - name: Get floating IP
        id: ip
        env:
          INSTANCE_COLLECTION_TAG: ${{ steps.build-config.outputs.COLLECTION_TAG }}
        run: |
          echo "::set-output name=value::$(php app/bin/console app:ip:get)"

      - name: Re-assign IP if found
        if: ${{ steps.ip.outputs.value != '' }}
        env:
          INSTANCE_COLLECTION_TAG: ${{ steps.build-config.outputs.COLLECTION_TAG }}
          COMMAND: "php app/bin/console app:ip:assign"
        run: ./ci/scripts/execute-command-output-json.sh

      - name: Create IP if none found
        if: ${{ steps.ip.outputs.value == '' }}
        env:
          INSTANCE_COLLECTION_TAG: ${{ steps.build-config.outputs.COLLECTION_TAG }}
          COMMAND: "php app/bin/console app:ip:create"
        run: ./ci/scripts/execute-command-output-json.sh
