name: Assign IP to Current Instance

on:
  pull_request:
    branches:
      - github-49
  workflow_dispatch:
  schedule:
    - cron: "20 * * * *"

jobs:
  commit:
    name: Assign IP
    runs-on: ubuntu-latest
    env:
      DIGITALOCEAN_API_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8

      - name: Download dependencies
        uses: php-actions/composer@v6
        with:
          args: --ignore-platform-reqs --quiet
          working_dir: app

      - name: Expose worker manager image variable
        id: worker-manager-image
        run:
          export echo $(cat worker-manager-image.env | tr '\n' ' ')

          echo "::set-output name=id::$WORKER_MANAGER_IMAGE"

      - name: Get floating IP
        id: floating-ip
        run: |
          cd app
          IP=$(php bin/console app:ip:get)
          HAS_IP="true"

          if [ -z "$IP" ]; then
            IP="null"
            HAS_IP="false"
          fi

          echo "::set-output name=ip::$IP"
          echo "::set-output name=has::$HAS_IP"

      - name: Create IP if none found
        if: ${{ steps.floating-ip.outputs.has == 'false' }}
        run: |
          cd app
          php bin/console app:ip:create

      - name: Re-assign IP if found
        if: ${{ steps.floating-ip.outputs.has == 'true' }}
        run: |
          cd app
          php bin/console app:ip:assign
