name: Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8

      - name: Download dependencies
        uses: php-actions/composer@v6
        with:
          args: --ignore-platform-reqs --quiet
          working_dir: app

      - name: Set version
        id: version
        env:
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          [[ ! -z "$RELEASE_TAG_NAME" ]] && echo "::set-output name=value::$RELEASE_TAG_NAME" || echo "::set-output name=value::master"

      - name: Set snapshot name
        id: snapshot_name
        env:
          EVENT_NAME: ${{ github.event_name }}
          PR_NUMBER: ${{ github.event.number }}
          RELEASE_VERSION: ${{ steps.version.outputs.value }}
        run: |
          cd app
          SNAPSHOT_NAME=$(
            php bin/console app:snapshot:create-name \
            --event-name $EVENT_NAME \
            --pull-request-number $PR_NUMBER \
            --release-version $RELEASE_VERSION
          )
          echo "::set-output name=value::$SNAPSHOT_NAME"

      - name: Verify snapshot name
        run: echo ${{ steps.snapshot_name.outputs.value }}

      - name: Install packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer

      - name: Verify packer installation
        run: |
          packer --version
          if [ $? -ne 0 ]; then exit 1; fi; exit 0;

      - name: Verify image configuration
        env:
          DIGITALOCEAN_API_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
          SNAPSHOT_NAME: ${{ steps.snapshot_name.outputs.value }}
        run: |
          export echo $(cat build.env | tr '\n' ' ')
          packer validate image.pkr.hcl

      - name: Create image and snapshot
        id: snapshot
        env:
          DIGITALOCEAN_API_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
          SNAPSHOT_NAME: ${{ steps.snapshot_name.outputs.value }}
        run: |
          export echo $(cat build.env | tr '\n' ' ')
          packer build image.pkr.hcl | tee packer.log
          ID=$(cat packer.log | tail -1 | grep -P -o 'ID: \d+' | tr -d 'ID: ')

          echo "::set-output name=id::$ID"

      - name: Verify snapshot exists
        env:
          DIGITALOCEAN_API_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
          ID: ${{ steps.snapshot.outputs.id }}
        run: |
          cd app
          php bin/console app:snapshot:exists --id $ID --expect-exists 1

      - name: Remove created image if not a release
        if: ${{ github.event_name != 'release' }}
        env:
          DIGITALOCEAN_API_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
          ID: ${{ steps.snapshot.outputs.id }}
        run: |
          cd app
          php bin/console app:snapshot:delete --id $ID
          php bin/console app:snapshot:exists --id $ID --expect-exists 0

      - name: Trigger update snapshot workflow if a release
        if: ${{ github.event_name == 'release' }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Update snapshot
          token: ${{ secrets.PAT_TOKEN_SELF }}
          inputs: '{ "snapshot_id": "${{ steps.snapshot.outputs.id }}", "commit_message": "Automatic snapshot.env for release ${{ github.event.release.tag_name }} ${{ steps.snapshot.outputs.id }}" }'
