name: Release Debug

on:
  pull_request:

jobs:
  build:
    name: Release Debug
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8

      - name: Download dependencies
        uses: php-actions/composer@v6
        with:
          args: --ignore-platform-reqs --quiet
          working_dir: app

      - name: Set version
        id: version
        env:
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          [[ ! -z "$RELEASE_TAG_NAME" ]] && echo "::set-output name=value::$RELEASE_TAG_NAME" || echo "::set-output name=value::master"

      - name: Read build config
        id: build-config
        env:
          ENV_FILE_PATH: ../build.env
        run: |
          cd app
          php bin/console app:env-file:read \
          --path $ENV_FILE_PATH \
          --output-format '::set-output name={{ name }}::{{ value }}'

      - name: Output build config
        env:
          WORKER_MANAGER_VERSION: ${{ steps.build-config.outputs.WORKER_MANAGER_VERSION }}
        run: |
          echo WORKER_MANAGER_VERSION $WORKER_MANAGER_VERSION

      - name: Set snapshot name
        id: snapshot_name
        env:
          EVENT_NAME: ${{ github.event_name }}
          PR_NUMBER: ${{ github.event.number }}
          RELEASE_VERSION: ${{ steps.version.outputs.value }}
        run: |
          cd app
          SNAPSHOT_NAME=$(
            php bin/console app:snapshot:create-name \
            --event-name $EVENT_NAME \
            --pull-request-number $PR_NUMBER \
            --release-version $RELEASE_VERSION
          )
          echo "::set-output name=value::$SNAPSHOT_NAME"
