name: service.configure

on:
  repository_dispatch:
    types: [service-configure]
  workflow_dispatch:
    inputs:
      service_id:
        description: The service for which the configuration is being stored
        required: true
      version:
        description: The service version
        required: true
      payload:
        description: "JSON object of key:value pairs"
        required: true

jobs:
  setup:
    name: Setup ${{ github.event.inputs.service_id }}
    runs-on: ubuntu-latest
    outputs:
      service_id: ${{ steps.service_id.outputs.value }}
      version: ${{ steps.version.outputs.value }}
      payload: ${{ steps.payload.outputs.value }}

    steps:
      - name: Output repository_dispatch inputs
        if: ${{ github.event_name == 'repository_dispatch' }}
        env:
          INPUTS: ${{ toJson(github.event.client_payload) }}
        run: echo "$INPUTS"

      - name: Output workflow_dispatch inputs
        env:
          INPUTS: ${{ toJson(github.event.inputs) }}
        run: echo "$INPUTS"

      - name: Checkout bash-ga-ci-tools
        uses: actions/checkout@v2
        with:
          repository: smartassert/bash-ga-ci-tools
          path: ./vendor/smartassert/bash-ga-ci-tools
          ref: main

      - name: Set service_id
        id: service_id
        env:
          VALUE1: ${{ github.event.client_payload.service_id }}
          VALUE2: ${{ github.event.inputs.service_id }}
        run: echo "::set-output name=value::$(./vendor/smartassert/bash-ga-ci-tools/src/select-exclusive-value-from-two-values.sh)"

      - name: Set version
        id: version
        env:
          VALUE1: ${{ github.event.client_payload.version }}
          VALUE2: ${{ github.event.inputs.version }}
        run: echo "::set-output name=value::$(./vendor/smartassert/bash-ga-ci-tools/src/select-exclusive-value-from-two-values.sh)"

      - name: Set payload
        id: payload
        env:
          VALUE1: ${{ github.event.client_payload.payload }}
          VALUE2: ${{ github.event.inputs.payload }}
        run: echo "::set-output name=value::$(./vendor/smartassert/bash-ga-ci-tools/src/select-exclusive-value-from-two-values.sh)"

  verify-setup:
    name: Verify setup ${{ needs.setup.outputs.service_id }}
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Output
        env:
          OUTPUTS: ${{ toJson(needs.setup.outputs) }}
        run: echo "$OUTPUTS"

      - name: Verify service_id, version payload are set
        env:
          SERVICE_ID: ${{ needs.setup.outputs.service_id }}
          VERSION: ${{ needs.setup.outputs.version }}
          PAYLOAD: ${{ needs.setup.outputs.payload }}
        run: |
          [[ -n "$SERVICE_ID" ]] || (echo "service_id not set" && exit 1)
          [[ -n "$VERSION" ]] || (echo "version not set" && exit 1)
          [[ -n "$PAYLOAD" ]] || (echo "payload not set" && exit 1)

  store:
    name: Store ${{ needs.setup.outputs.service_id }}
    runs-on: ubuntu-latest
    needs: [setup, verify-setup]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set path for bash-ga-ci-tools
        id: bash-ga-ci-tools
        run: |
          echo "::set-output name=path::./vendor/smartassert/bash-ga-ci-tools"

      - name: Checkout bash-ga-ci-tools
        uses: actions/checkout@v2
        with:
          repository: smartassert/bash-ga-ci-tools
          path: ${{ steps.bash-ga-ci-tools.outputs.path }}
          ref: main

      - name: Store service configuration
        env:
          CONFIGURATION_PATH: ./services/${{ needs.setup.outputs.service_id }}/configuration.json
          VERSION: ${{ needs.setup.outputs.version }}
          PAYLOAD: ${{ needs.setup.outputs.payload }}
        run: |
          VERSION_JSON_TEMPLATE='{"version": "{{ version }}"}'
          VERSION_JSON="${VERSION_JSON_TEMPLATE/"{{ version }}"/$VERSION}"

          JSON=$(./vendor/smartassert/bash-ga-ci-tools/src/combine-json-scalar-objects.sh "$PAYLOAD" "$VERSION_JSON")

          mkdir -p "$(dirname "$CONFIGURATION_PATH")"

          jq "." <<< "$JSON" > "$CONFIGURATION_PATH"

      - name: Remove bash-ga-ci-tools
        run: rm -Rf ${{ steps.bash-ga-ci-tools.outputs.path }}

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automatic configuration update for ${{ needs.setup.outputs.service_id }} ${{ needs.setup.outputs.version }}"
