name: service.configure

on:
  repository_dispatch:
    types: [service-configure]
  workflow_dispatch:
    inputs:
      service_id:
        description: The service for which the configuration is being stored
        required: true
      build_configuration:
        description: "JSON scalar object of key:value pairs"
        required: true

jobs:
  configure_service:
    name: Configure ${{ github.event.inputs.service_id }}
    runs-on: ubuntu-latest

    steps:
      - name: Output repository_dispatch inputs
        if: ${{ github.event_name == 'repository_dispatch' }}
        env:
          INPUTS: ${{ toJson(github.event.client_payload) }}
        run: echo "$INPUTS"

      - name: Output workflow_dispatch inputs
        env:
          INPUTS: ${{ toJson(github.event.inputs) }}
        run: echo "$INPUTS"

      - name: Set service_id
        env:
          REPOSITORY_DISPATCH_VALUE: ${{ github.event.client_payload.service_id }}
          WORKFLOW_DISPATCH_VALUE: ${{ github.event.inputs.service_id }}
        run: echo "service_id=${REPOSITORY_DISPATCH_VALUE:-$WORKFLOW_DISPATCH_VALUE}" >> "$GITHUB_ENV"

      - name: Set build configuration
        env:
          REPOSITORY_DISPATCH_VALUE: ${{ github.event.client_payload.build_configuration }}
          WORKFLOW_DISPATCH_VALUE: ${{ github.event.inputs.build_configuration }}
        run: echo "build_configuration=${REPOSITORY_DISPATCH_VALUE:-$WORKFLOW_DISPATCH_VALUE}" >> "$GITHUB_ENV"

      - name: Verify setup
        env:
          SERVICE_ID: ${{ env.service_id }}
          BUILD_CONFIGURATION: ${{ env.build_configuration }}
        run: |
          if [ "" = "$SERVICE_ID" ]; then
            echo "service_id not set"
            exit 1
          fi

          if [ "" = "$BUILD_CONFIGURATION" ]; then
            echo "configuration not set"
            exit 1
          fi

          echo "service_id: $SERVICE_ID"
          echo "build_configuration: $BUILD_CONFIGURATION"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Store service build configuration
        env:
          CONFIGURATION_PATH: ./services/${{ env.service_id }}/build_configuration.json
          BUILD_CONFIGURATION: ${{ env.build_configuration }}
        run: |
          mkdir -p "$(dirname "$CONFIGURATION_PATH")"
          jq -S '.' <<< "$BUILD_CONFIGURATION" > "$CONFIGURATION_PATH"

      - name: Set commit message
        run: echo "commit_message=Automatic build configuration update for ${{ env.service_id }} $(date '+%Y-%m-%d %H:%M:%S')" >> "$GITHUB_ENV"

      - name: Commit
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "${{ env.commit_message }}"

      - name: Trigger image.build
        if: ${{ steps.commit.outputs.changes_detected == 'true' }}
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN_SELF }}
          SERVICE_ID: ${{ env.service_id }}
        run: |
          gh workflow run image.build.yml -f service_id="$SERVICE_ID" -f should_deploy="true"
