name: service.configure

on:
  workflow_dispatch:
    inputs:
      service_id:
        description: The service for which the configuration is being stored
        required: true
      image_id:
        description: ID of the snapshot to store
        required: true
      state_url:
        description: URL from which to get instance state
        required: true
      health_check_url:
        description: URL from which to check that an instance is healthy
        required: true

jobs:
  setup:
    name: Setup ${{ github.event.inputs.service_id }}
    runs-on: ubuntu-latest

    steps:
      - name: Output event inputs
        env:
          INPUTS: ${{ toJson(github.event.inputs) }}
        run: echo "$INPUTS"

      - name: Validate event inputs
        env:
          SERVICE_ID: ${{ github.event.inputs.service_id }}
          IMAGE_ID: ${{ github.event.inputs.service_id }}
        run: |
          [[ -n "$SERVICE_ID" ]] || (echo "Event service_id not set" && exit 1)
          [[ -n "$IMAGE_ID" ]] || (echo "Event image_id not set" && exit 1)

  store:
    name: Store ${{ github.event.inputs.service_id }}
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Define service configuration directory
        id: directory_path
        env:
          SERVICE_ID: ${{ github.event.inputs.service_id }}
        run: echo "::set-output name=value::./services/$SERVICE_ID"

      - name: Create service configuration directory
        env:
          DIRECTORY: ${{ steps.directory_path.outputs.value }}
        run: mkdir -p "$DIRECTORY"

      - name: Store service configuration
        env:
          DIRECTORY: ${{ steps.directory_path.outputs.value }}
          SERVICE_ID: ${{ github.event.inputs.service_id }}
          IMAGE_ID: ${{ github.event.inputs.service_id }}
          STATE_URL: ${{ github.event.inputs.state_url }}
          HEALTH_CHECK_URL: ${{ github.event.inputs.health_check_url }}
        run: |
          ./ci/scripts/create-service-configuration-content.sh > "$DIRECTORY/configuration.env"
          ls -la "$DIRECTORY"
          cat "$DIRECTORY/configuration.env"
