name: Static Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  caddy_fmt:
    name: Caddy fmt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate users Caddyfile
        run: |
          ORIGINAL=$(< ./services/users/caddy/Caddyfile)
          FORMATTED=$(docker run -v "$PWD/services/users/caddy/Caddyfile:/etc/caddy/Caddyfile" caddy caddy fmt /etc/caddy/Caddyfile)

          [[ "$ORIGINAL" = "$FORMATTED" ]]

  caddy_validate:
    name: Caddy validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate users Caddyfile
        env:
          SERVICE_ID: users
        run: ./ci/validate-caddyfile.sh

      - name: Validate worker-manager Caddyfile
        env:
          SERVICE_ID: worker-manager
        run: ./ci/validate-caddyfile.sh

  actionlint:
    name: Actionlint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run actionlint
        run: docker run --rm -v "$PWD:/repo" --workdir /repo rhysd/actionlint:latest -color

  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run
        run: |
          docker run --rm -v "$PWD:/mnt" koalaman/shellcheck:stable ./ci/*.sh
          docker run --rm -v "$PWD:/mnt" koalaman/shellcheck:stable ./provisioner/*.sh
          docker run --rm -v "$PWD:/mnt" koalaman/shellcheck:stable ./services/**/*.sh
