name: Static Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      service_ids: ${{ steps.service_ids.outputs.value }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set service ids
        id: service_ids
        run: |
          OUTPUT="["
          SERVICE_IDS=$(ls services)
          
          for SERVICE_ID in $SERVICE_IDS; do
            OUTPUT="$OUTPUT'$SERVICE_ID', "
          done
          
          OUTPUT="$OUTPUT]"
          
          echo "::set-output name=value::$OUTPUT"

  caddy_fmt:
    needs: setup
    name: Caddy fmt
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service_id: ${{ fromJson(needs.setup.outputs.service_ids) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check format of service Caddyfiles
        run: |
          CADDYFILE_PATH="$PWD/services/${{ matrix.service_id }}/caddy/Caddyfile" ./ci/verify-caddyfile-is-correctly-formatted.sh

  caddy_validate:
    needs: setup
    name: Caddy validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service_id: ${{ fromJson(needs.setup.outputs.service_ids) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate service Caddyfiles
        run: |
          CADDYFILE_PATH="$PWD/services/${{ matrix.service_id }}/caddy/Caddyfile" ./ci/validate-caddyfile.sh

  packer_validate:
    needs: setup
    name: Packer validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service_id: ${{ fromJson(needs.setup.outputs.service_ids) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate service packer definition
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: "$PWD/services/${{ matrix.service_id }}/image.pkr.hcl"

  actionlint:
    name: Actionlint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run actionlint
        run: docker run --rm -v "$PWD:/repo" --workdir /repo rhysd/actionlint:latest -color

  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run
        run: |
          docker run --rm -v "$PWD:/mnt" koalaman/shellcheck:stable ./ci/*.sh
          docker run --rm -v "$PWD:/mnt" koalaman/shellcheck:stable ./provisioner/*.sh
          docker run --rm -v "$PWD:/mnt" koalaman/shellcheck:stable ./services/**/*.sh
