name: Static Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  caddy_validate:
    name: Caddy validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate users Caddyfile
        run: |
          docker run \
            -e DOMAIN="example.com" \
            -v "$PWD/services/users/caddy/Caddyfile:/etc/caddy/Caddyfile" \
            caddy caddy validate --config /etc/caddy/Caddyfile


  actionlint:
    name: Actionlint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run actionlint
        run: docker run --rm -v "$PWD:/repo" --workdir /repo rhysd/actionlint:latest -color
