name: Static Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  caddy_fmt:
    name: Caddy fmt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check format of common Caddyfile
        env:
          CADDYFILE_PATH: caddy-common/Caddyfile
        run: CADDYFILE_PATH="$PWD/$CADDYFILE_PATH" ./ci/verify-caddyfile-is-correctly-formatted.sh

  caddy_validate:
    name: Caddy validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate common Caddyfile
        env:
          CADDYFILE_PATH: caddy-common/Caddyfile
        run: CADDYFILE_PATH="$PWD/$CADDYFILE_PATH" ./ci/validate-caddyfile.sh

  actionlint:
    name: Actionlint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run actionlint
        run: docker run --rm -v "$PWD:/repo" --workdir /repo rhysd/actionlint:latest -color

  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run
        run: |
          docker run --rm -v "$PWD:/mnt" koalaman/shellcheck:stable ./ci/*.sh
          docker run --rm -v "$PWD:/mnt" koalaman/shellcheck:stable ./provisioner/*.sh
          docker run --rm -v "$PWD:/mnt" koalaman/shellcheck:stable ./services/**/*.sh
