name: Update worker manager image

on:
  workflow_dispatch:
    inputs:
      snapshot_id:
        description: ID of the snapshot to store
        required: true
      commit_message:
        description: Commit message
        required: true

jobs:
  commit:
    name: Update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN_SELF }}

      - name: Store
        env:
          ID: ${{ github.event.inputs.image }}
        run:  echo "WORKER_MANAGER_IMAGE=$ID" > worker-manager-image.env

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "${{ github.event.inputs.commit_message }}"
