name: Update snapshot

on:
  workflow_dispatch:
    inputs:
      snapshot_id:
        description: ID of the snapshot to store
        required: true
      commit_message:
        description: Commit message
        required: true

jobs:
  commit:
    name: Update snapshot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN_SELF }}

      - name: Store snapshot ID
        id: update
        env:
          ID: ${{ github.event.inputs.snapshot_id }}
        run:  echo "SNAPSHOT=$ID" > snapshot.env

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "${{ github.event.inputs.commit_message }}"
