name: Update snapshot

on:
  workflow_dispatch:
    inputs:
      snapshot_id:
        description: ID of the snapshot to store
        required: true
      release_tag:
        description: Release tag
        required: true

jobs:
  commit:
    name: Update snapshot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN_SELF }}

      - name: Debug - git status (which branch are we on?)
        run: git status

      - name: Store snapshot ID
        id: update
        env:
          ID: ${{ github.event.inputs.snapshot_id }}
        run: |
          cp snapshot.env snapshot.old
          rm -f snapshot.env
          echo "SNAPSHOT=$ID" >> snapshot.env

          if cmp --quiet snapshot.env snapshot.old ; then
            echo "::set-output name=has_changes::false"
          else
            echo "::set-output name=has_changes::true"
          fi

          rm snapshot.old

      - name: Debug - git status (examine changes to commit)
        run: git status

#      - name: Commit changes
#        if: ${{ steps.update-snapshot.outputs.has_changes == 'true' }}
#        uses: stefanzweifel/git-auto-commit-action@v4
#        with:
#          commit_message: "Automatic snapshot.env for release ${{ github.event.inputs.release_tag }} ${{ github.event.inputs.snapshot_id }}"
