name: Upload Artifact POC

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
