name: VirtualBox VM

on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: macos-10.15

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read build config
        id: build-config
        env:
          ENV_FILE_PATH: ./build.env
        run: ./ci/read-env-file.sh

      - name: Output build config
        env:
          WORKER_MANAGER_VERSION: ${{ steps.build-config.outputs.WORKER_MANAGER_VERSION }}
        run: printenv

      - name: Show package versions
        run: |
          vagrant --version
          VBoxManage --version

      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/.vagrant.d/boxes/focal-server-cloudimg-amd64-vagrant
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Validate Vagrantfile
        run: vagrant validate

      - name: Lint provision.sh
        run: |
          brew install shellcheck
          shellcheck provision.sh

      - name: Vagrant up
        env:
          HOST_PORT: 80
          DIGITALOCEAN_API_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
        run: (export echo $(cat build.env | tr '\n' ' '); vagrant up)
